# https://cmake.org/cmake/help/latest/module/CMakeGraphVizOptions.html

set( GRAPHVIZ_GRAPH_NAME "CARPC" )
set( GRAPHVIZ_GRAPH_HEADER 12 )
set( GRAPHVIZ_NODE_PREFIX "@TDA" )

set( GRAPHVIZ_EXECUTABLES TRUE )
set( GRAPHVIZ_STATIC_LIBS TRUE )
set( GRAPHVIZ_SHARED_LIBS TRUE )
set( GRAPHVIZ_MODULE_LIBS TRUE )
set( GRAPHVIZ_INTERFACE_LIBS TRUE )
set( GRAPHVIZ_OBJECT_LIBS TRUE )
set( GRAPHVIZ_UNKNOWN_LIBS TRUE )
set( GRAPHVIZ_EXTERNAL_LIBS TRUE )
set( GRAPHVIZ_CUSTOM_TARGETS TRUE )
set( GRAPHVIZ_IGNORE_TARGETS )
set( GRAPHVIZ_GENERATE_PER_TARGET TRUE )
set( GRAPHVIZ_GENERATE_DEPENDERS TRUE )
