include ./Makefile.variables



all: 
	reset
	@echo "Common target is not defined."
	@echo "Please, specify make target."

execute:
	reset
	@echo "'execute' target is not defined."
	@echo "Please, specify make target."

debug:
	reset
	@echo "'debug' target is not defined."
	@echo "Please, specify make target."

config:
	reset

clean: config \
	$(PROJECT_HOOKS_NAME)_clean \
	$(PROJECT_FRAMEWORK_NAME)_clean \
	$(PROJECT_SERVICEBROCKER_NAME)_clean \
	$(PROJECT_APPLICATION_NAME)_clean \
	$(PROJECT_CORE_NAME)_clean \
	$(PROJECT_CONTROLLER_NAME)_clean \
	$(PROJECT_HMI_NAME)_clean \
	$(PROJECT_EXPERIMENTAL_NAME)_clean \

build: config \
	$(PROJECT_HOOKS_NAME)_build \
	$(PROJECT_FRAMEWORK_NAME)_build \
	$(PROJECT_SERVICEBROCKER_NAME)_build \
	$(PROJECT_APPLICATION_NAME)_build \
	$(PROJECT_CORE_NAME)_build \
	$(PROJECT_CONTROLLER_NAME)_build \
	$(PROJECT_HMI_NAME)_build \
	$(PROJECT_EXPERIMENTAL_NAME)_build \

clean_build: clean build

generate: config \
	$(PROJECT_HOOKS_NAME)_generate \
	$(PROJECT_FRAMEWORK_NAME)_generate \
	$(PROJECT_SERVICEBROCKER_NAME)_generate \
	$(PROJECT_APPLICATION_NAME)_generate \
	$(PROJECT_CORE_NAME)_generate \
	$(PROJECT_CONTROLLER_NAME)_generate \
	$(PROJECT_HMI_NAME)_generate \
	$(PROJECT_EXPERIMENTAL_NAME)_generate \

info: config \
	$(PROJECT_HOOKS_NAME)_info \
	$(PROJECT_FRAMEWORK_NAME)_info \
	$(PROJECT_SERVICEBROCKER_NAME)_info \
	$(PROJECT_APPLICATION_NAME)_info \
	$(PROJECT_CORE_NAME)_info \
	$(PROJECT_CONTROLLER_NAME)_info \
	$(PROJECT_HMI_NAME)_info \
	$(PROJECT_EXPERIMENTAL_NAME)_info \

archive: clean
	@$(TAR) -cvf $(ROOT_DIR)/../$(PROJECT_NAME)_$(DATE)_$(TIME).tar ../$(PROJECT_NAME)



$(PROJECT_FRAMEWORK_NAME)_build:
	$(MAKE) -C $(PROJECT_FRAMEWORK_DIR) build $(FRAMEWORK_MAKE_PARAMS)

$(PROJECT_FRAMEWORK_NAME)_generate:
	$(MAKE) -C $(PROJECT_FRAMEWORK_DIR) generate $(FRAMEWORK_MAKE_PARAMS)

$(PROJECT_FRAMEWORK_NAME)_clean:
	$(MAKE) -C $(PROJECT_FRAMEWORK_DIR) clean $(FRAMEWORK_MAKE_PARAMS)

$(PROJECT_FRAMEWORK_NAME)_info:
	$(MAKE) -C $(PROJECT_FRAMEWORK_DIR) info $(FRAMEWORK_MAKE_PARAMS)

$(PROJECT_FRAMEWORK_NAME)_archive:
	$(MAKE) -C $(PROJECT_FRAMEWORK_DIR) archive $(FRAMEWORK_MAKE_PARAMS)



$(PROJECT_SERVICEBROCKER_NAME)_build:
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) build $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_generate:
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) generate $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_clean:
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) clean $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_info:
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) info $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_archive:
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) archive $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_execute:
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) execute $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_debug:
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) debug $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_disassm:
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) disassm $(SERVICEBROCKER_MAKE_PARAMS)



$(PROJECT_HOOKS_NAME)_build:
	$(MAKE) -C $(PROJECT_HOOKS_DIR) build $(HOOKS_MAKE_PARAMS)

$(PROJECT_HOOKS_NAME)_generate:
	$(MAKE) -C $(PROJECT_HOOKS_DIR) generate $(HOOKS_MAKE_PARAMS)

$(PROJECT_HOOKS_NAME)_clean:
	$(MAKE) -C $(PROJECT_HOOKS_DIR) clean $(HOOKS_MAKE_PARAMS)

$(PROJECT_HOOKS_NAME)_info:
	$(MAKE) -C $(PROJECT_HOOKS_DIR) info $(HOOKS_MAKE_PARAMS)

$(PROJECT_HOOKS_NAME)_archive:
	$(MAKE) -C $(PROJECT_HOOKS_DIR) archive $(HOOKS_MAKE_PARAMS)

$(PROJECT_HOOKS_NAME)_execute:
	$(MAKE) -C $(PROJECT_HOOKS_DIR) execute $(HOOKS_MAKE_PARAMS)



$(PROJECT_APPLICATION_NAME)_build:
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) build $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_generate:
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) generate $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_clean:
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) clean $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_info:
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) info $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_archive:
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) archive $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_execute:
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) execute $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_pexecute:
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) pexecute $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_debug:
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) debug $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_disassm:
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) disassm $(APPLICATION_MAKE_PARAMS)



$(PROJECT_CORE_NAME)_build:
	$(MAKE) -C $(PROJECT_CORE_DIR) build $(CORE_MAKE_PARAMS)

$(PROJECT_CORE_NAME)_generate:
	$(MAKE) -C $(PROJECT_CORE_DIR) generate $(CORE_MAKE_PARAMS)

$(PROJECT_CORE_NAME)_clean:
	$(MAKE) -C $(PROJECT_CORE_DIR) clean $(CORE_MAKE_PARAMS)

$(PROJECT_CORE_NAME)_info:
	$(MAKE) -C $(PROJECT_CORE_DIR) info $(CORE_MAKE_PARAMS)

$(PROJECT_CORE_NAME)_archive:
	$(MAKE) -C $(PROJECT_CORE_DIR) archive $(CORE_MAKE_PARAMS)

$(PROJECT_CORE_NAME)_execute:
	$(MAKE) -C $(PROJECT_CORE_DIR) execute $(CORE_MAKE_PARAMS)

$(PROJECT_CORE_NAME)_pexecute:
	$(MAKE) -C $(PROJECT_CORE_DIR) pexecute $(CORE_MAKE_PARAMS)

$(PROJECT_CORE_NAME)_debug:
	$(MAKE) -C $(PROJECT_CORE_DIR) debug $(CORE_MAKE_PARAMS)

$(PROJECT_CORE_NAME)_disassm:
	$(MAKE) -C $(PROJECT_CORE_DIR) disassm $(CORE_MAKE_PARAMS)



$(PROJECT_CONTROLLER_NAME)_build:
	$(MAKE) -C $(PROJECT_CONTROLLER_DIR) build $(CONTROLLER_MAKE_PARAMS)

$(PROJECT_CONTROLLER_NAME)_generate:
	$(MAKE) -C $(PROJECT_CONTROLLER_DIR) generate $(CONTROLLER_MAKE_PARAMS)

$(PROJECT_CONTROLLER_NAME)_clean:
	$(MAKE) -C $(PROJECT_CONTROLLER_DIR) clean $(CONTROLLER_MAKE_PARAMS)

$(PROJECT_CONTROLLER_NAME)_info:
	$(MAKE) -C $(PROJECT_CONTROLLER_DIR) info $(CONTROLLER_MAKE_PARAMS)

$(PROJECT_CONTROLLER_NAME)_archive:
	$(MAKE) -C $(PROJECT_CONTROLLER_DIR) archive $(CONTROLLER_MAKE_PARAMS)

$(PROJECT_CONTROLLER_NAME)_execute:
	$(MAKE) -C $(PROJECT_CONTROLLER_DIR) execute $(CONTROLLER_MAKE_PARAMS)

$(PROJECT_CONTROLLER_NAME)_pexecute:
	$(MAKE) -C $(PROJECT_CONTROLLER_DIR) pexecute $(CONTROLLER_MAKE_PARAMS)

$(PROJECT_CONTROLLER_NAME)_debug:
	$(MAKE) -C $(PROJECT_CONTROLLER_DIR) debug $(CONTROLLER_MAKE_PARAMS)

$(PROJECT_CONTROLLER_NAME)_disassm:
	$(MAKE) -C $(PROJECT_CONTROLLER_DIR) disassm $(CONTROLLER_MAKE_PARAMS)



$(PROJECT_HMI_NAME)_build:
	$(MAKE) -C $(PROJECT_HMI_DIR) build $(HMI_MAKE_PARAMS)

$(PROJECT_HMI_NAME)_generate:
	$(MAKE) -C $(PROJECT_HMI_DIR) generate $(HMI_MAKE_PARAMS)

$(PROJECT_HMI_NAME)_clean:
	$(MAKE) -C $(PROJECT_HMI_DIR) clean $(HMI_MAKE_PARAMS)

$(PROJECT_HMI_NAME)_info:
	$(MAKE) -C $(PROJECT_HMI_DIR) info $(HMI_MAKE_PARAMS)

$(PROJECT_HMI_NAME)_archive:
	$(MAKE) -C $(PROJECT_HMI_DIR) archive $(HMI_MAKE_PARAMS)

$(PROJECT_HMI_NAME)_execute:
	$(MAKE) -C $(PROJECT_HMI_DIR) execute $(HMI_MAKE_PARAMS)

$(PROJECT_HMI_NAME)_pexecute:
	$(MAKE) -C $(PROJECT_HMI_DIR) pexecute $(HMI_MAKE_PARAMS)

$(PROJECT_HMI_NAME)_debug:
	$(MAKE) -C $(PROJECT_HMI_DIR) debug $(HMI_MAKE_PARAMS)

$(PROJECT_HMI_NAME)_disassm:
	$(MAKE) -C $(PROJECT_HMI_DIR) disassm $(HMI_MAKE_PARAMS)



$(PROJECT_EXPERIMENTAL_NAME)_build:
	$(MAKE) -C $(PROJECT_EXPERIMENTAL_DIR) build $(EXPERIMENTAL_MAKE_PARAMS)

$(PROJECT_EXPERIMENTAL_NAME)_generate:
	$(MAKE) -C $(PROJECT_EXPERIMENTAL_DIR) generate $(EXPERIMENTAL_MAKE_PARAMS)

$(PROJECT_EXPERIMENTAL_NAME)_clean:
	$(MAKE) -C $(PROJECT_EXPERIMENTAL_DIR) clean $(EXPERIMENTAL_MAKE_PARAMS)

$(PROJECT_EXPERIMENTAL_NAME)_info:
	$(MAKE) -C $(PROJECT_EXPERIMENTAL_DIR) info $(EXPERIMENTAL_MAKE_PARAMS)

$(PROJECT_EXPERIMENTAL_NAME)_archive:
	$(MAKE) -C $(PROJECT_EXPERIMENTAL_DIR) archive $(EXPERIMENTAL_MAKE_PARAMS)

$(PROJECT_EXPERIMENTAL_NAME)_execute:
	$(MAKE) -C $(PROJECT_EXPERIMENTAL_DIR) execute $(EXPERIMENTAL_MAKE_PARAMS)

$(PROJECT_EXPERIMENTAL_NAME)_pexecute:
	$(MAKE) -C $(PROJECT_EXPERIMENTAL_DIR) pexecute $(EXPERIMENTAL_MAKE_PARAMS)

$(PROJECT_EXPERIMENTAL_NAME)_debug:
	$(MAKE) -C $(PROJECT_EXPERIMENTAL_DIR) debug $(EXPERIMENTAL_MAKE_PARAMS)

$(PROJECT_EXPERIMENTAL_NAME)_disassm:
	$(MAKE) -C $(PROJECT_EXPERIMENTAL_DIR) disassm $(EXPERIMENTAL_MAKE_PARAMS)







# Non-File Targets
.PHONY: all
