include ./Makefile.variables




all: 
	reset
	@echo "Common target is not defined."
	@echo "Please, specify make target."


FRAMEWORK_MAKE_PARAMS     := PROJECT_NAME=$(PROJECT_FRAMEWORK_NAME) PROJECT_DIR=$(PROJECT_FRAMEWORK_DIR) PRODUCT_DIR=$(PRODUCT_FRAMEWORK_DIR)

$(PROJECT_FRAMEWORK_NAME)_$(TARGET_BUILD):
	$(MAKE) -C $(PROJECT_FRAMEWORK_DIR) $(TARGET_BUILD) $(FRAMEWORK_MAKE_PARAMS)

$(PROJECT_FRAMEWORK_NAME)_$(TARGET_GENERATE):
	$(MAKE) -C $(PROJECT_FRAMEWORK_DIR) $(TARGET_GENERATE) $(FRAMEWORK_MAKE_PARAMS)

$(PROJECT_FRAMEWORK_NAME)_$(TARGET_CLEAN):
	$(MAKE) -C $(PROJECT_FRAMEWORK_DIR) $(TARGET_CLEAN) $(FRAMEWORK_MAKE_PARAMS)

$(PROJECT_FRAMEWORK_NAME)_$(TARGET_INFO):
	$(MAKE) -C $(PROJECT_FRAMEWORK_DIR) $(TARGET_INFO) $(FRAMEWORK_MAKE_PARAMS)

$(PROJECT_FRAMEWORK_NAME)_$(TARGET_ARCHIVE):
	$(MAKE) -C $(PROJECT_FRAMEWORK_DIR) $(TARGET_ARCHIVE) $(FRAMEWORK_MAKE_PARAMS)



APPLICATION_MAKE_PARAMS     := PROJECT_NAME=$(PROJECT_APPLICATION_NAME) PROJECT_DIR=$(PROJECT_APPLICATION_DIR) PRODUCT_DIR=$(PRODUCT_APPLICATION_DIR)

$(PROJECT_APPLICATION_NAME)_$(TARGET_BUILD):
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) $(TARGET_BUILD) $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_$(TARGET_GENERATE):
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) $(TARGET_GENERATE) $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_$(TARGET_CLEAN):
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) $(TARGET_CLEAN) $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_$(TARGET_INFO):
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) $(TARGET_INFO) $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_$(TARGET_ARCHIVE):
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) $(TARGET_ARCHIVE) $(APPLICATION_MAKE_PARAMS)

$(PROJECT_APPLICATION_NAME)_$(TARGET_EXECUTE):
	$(MAKE) -C $(PROJECT_APPLICATION_DIR) $(TARGET_EXECUTE) $(APPLICATION_MAKE_PARAMS)



SERVICEBROCKER_MAKE_PARAMS   := PROJECT_NAME=$(PROJECT_SERVICEBROCKER_NAME) PROJECT_DIR=$(PROJECT_SERVICEBROCKER_DIR) PRODUCT_DIR=$(PRODUCT_SERVICEBROCKER_DIR)

$(PROJECT_SERVICEBROCKER_NAME)_$(TARGET_BUILD):
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) $(TARGET_BUILD) $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_$(TARGET_GENERATE):
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) $(TARGET_GENERATE) $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_$(TARGET_CLEAN):
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) $(TARGET_CLEAN) $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_$(TARGET_INFO):
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) $(TARGET_INFO) $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_$(TARGET_ARCHIVE):
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) $(TARGET_ARCHIVE) $(SERVICEBROCKER_MAKE_PARAMS)

$(PROJECT_SERVICEBROCKER_NAME)_$(TARGET_EXECUTE):
	$(MAKE) -C $(PROJECT_SERVICEBROCKER_DIR) $(TARGET_EXECUTE) $(SERVICEBROCKER_MAKE_PARAMS)





$(TARGET_BUILD): $(PROJECT_FRAMEWORK_NAME)_$(TARGET_BUILD) $(PROJECT_APPLICATION_NAME)_$(TARGET_BUILD) $(PROJECT_SERVICEBROCKER_NAME)_$(TARGET_BUILD)

$(TARGET_GENERATE): $(PROJECT_FRAMEWORK_NAME)_$(TARGET_GENERATE) $(PROJECT_APPLICATION_NAME)_$(TARGET_GENERATE) $(PROJECT_SERVICEBROCKER_NAME)_$(TARGET_GENERATE)

$(TARGET_CLEAN): $(PROJECT_FRAMEWORK_NAME)_$(TARGET_CLEAN) $(PROJECT_APPLICATION_NAME)_$(TARGET_CLEAN) $(PROJECT_SERVICEBROCKER_NAME)_$(TARGET_CLEAN)

$(TARGET_INFO): $(PROJECT_FRAMEWORK_NAME)_$(TARGET_INFO) $(PROJECT_APPLICATION_NAME)_$(TARGET_INFO) $(PROJECT_SERVICEBROCKER_NAME)_$(TARGET_INFO)

$(TARGET_ARCHIVE):
	@$(TAR) -cvf $(ROOT_DIR)/../$(PROJECT_NAME)_$(DATE)_$(TIME).tar $(ROOT_DIR)

$(TARGET_EXECUTE):



# Non-File Targets
.PHONY: all
