version 1.0.0

interface onoff
{
   request: trigger_state(
      std::string& state,
      std::size_t timeout
   ) trigger_state;

   response: trigger_state(
      bool result
   );

   request: start( );

   attribute: std::string current_state;
}
