#pragma once



#define BOOL_TO_STRING( value ) ( value ? "true" : "false" )

#define CONCAT_STRINGS_2( STRING1, STRING2                                                ) STRING1 STRING2
#define CONCAT_STRINGS_3( STRING1, STRING2, STRING3                                       ) STRING1 STRING2 STRING3
#define CONCAT_STRINGS_4( STRING1, STRING2, STRING3, STRING4                              ) STRING1 STRING2 STRING3 STRING4
#define CONCAT_STRINGS_5( STRING1, STRING2, STRING3, STRING4, STRING5                     ) STRING1 STRING2 STRING3 STRING4 STRING5
#define CONCAT_STRINGS_6( STRING1, STRING2, STRING3, STRING4, STRING5, STRING6            ) STRING1 STRING2 STRING3 STRING4 STRING5 STRING6
#define CONCAT_STRINGS_7( STRING1, STRING2, STRING3, STRING4, STRING5, STRING6, STRING7   ) STRING1 STRING2 STRING3 STRING4 STRING5 STRING6 STRING7
