name: Build linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'
        required: true
        default: 'main'

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:

    # Install dlt
    - name: Install dlt
      run: sudo apt install libdlt-dev
      shell: bash

    # Install google protobuf
    - name: Install google protobuf
      run: sudo apt install libprotobuf-dev protobuf-compiler
      shell: bash

    # Install python and pip
    - name: Install python and python-pip
      run: sudo apt install python3 python3-pip
      shell: bash

    # Install python antlr4 runtime
    - name: Install python-antlr4
      run: pip install antlr4-python3-runtime
      shell: bash

    # Checkout project's revision, which is pushed
    - name: Checkout of the project
      uses: actions/checkout@v2
      with:
        repository: dterletskiy/${{ github.event.repository.name }}
        path: ./${{ github.event.repository.name }}
        ref: ${{ github.ref }}

    # Submodules update
    - name: Update submodules
      run: git submodule update --init --recursive
      shell: bash
      working-directory: ./${{ github.event.repository.name }}

    # CMake configure
    - name: Configure
      run: cmake -S ${PWD} -B ${PWD}/out/build --install-prefix ${PWD}/out/delivery --graphviz=${PWD}/out/doc/graph/carpc
      shell: bash
      working-directory: ./${{ github.event.repository.name }}

    # CMake build
    - name: Build
      run: cmake --build ${PWD}/out/build -j 8
      shell: bash
      working-directory: ./${{ github.event.repository.name }}

    # CMake install
    - name: Install
      run: cmake --build ${PWD}/out/build --target install
      shell: bash
      working-directory: ./${{ github.event.repository.name }}
